sudo: false
dist: trusty
language: c

compiler:
  - clang
  - gcc

env:
  - GOAL=stm32
  - GOAL=unix

matrix:
  exclude:
    - compiler: clang
      env: GOAL=stm32

addons:
  apt:
    packages:
    - build-essential
    - gcc-multilib
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi

install:
    - pip3 install ed25519 pyblake2

script:
  - test "$GOAL" != "stm32" || test "$CC" != "gcc" || make vendorheader
  - test "$GOAL" != "stm32" || test "$CC" != "gcc" || make build_cross
  - test "$GOAL" != "stm32" || test "$CC" != "gcc" || make build_boardloader
  - test "$GOAL" != "stm32" || test "$CC" != "gcc" || make build_bootloader
  - test "$GOAL" != "stm32" || test "$CC" != "gcc" || make build_firmware

  - test "$GOAL" != "unix" || make build_unix TREZOR_NOUI=1
  - test "$GOAL" != "unix" || make test

notifications:
  webhooks:
    urls:
      - http://sway.gk2.sk:5000/travis
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always
