sudo: false
dist: trusty
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - build-essential
    - gcc-multilib
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi

install:
    - pip3 install ed25519 pyblake2

script:
  - test "$CC" = "clang" || make vendorheader

  - test "$CC" = "clang" || make build_cross

  - test "$CC" = "clang" || make build_boardloader

  - test "$CC" = "clang" || make build_bootloader

  - test "$CC" = "clang" || make build_firmware

  - make build_unix TREZOR_NOUI=1

  - test "$CC" = "clang" || make test

notifications:
  webhooks:
    urls:
      - http://sway.gk2.sk:5000/travis
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always
