sudo: false
dist: trusty
language: c

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - check
    - cmake
    - cmake-data
    - libssl-dev
    - python-pip

install:
  - pip install --user pytest ecdsa curve25519-donna

script:
  - export CC='gcc-5'
  - make
  - ./tests
  - ./test-openssl 1000
  - ITERS=10 py.test
  - mkdir _build && cd _build
  - cmake ..
  - make
