dist: trusty

language: c

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential gcc-multilib gcc-arm-embedded

script:
  - make vendorheader

  - make build_cross

  - make build_bootloader

  - make build_loader

  - make build_firmware

  - make build_unix TREZOR_NOUI=1

  - make test

notifications:
  webhooks:
    urls:
      - http://sway.gk2.sk:5000/travis
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always
