sudo: false
dist: trusty
language: c

compiler:
  - clang
  - gcc

env:
  - GOAL=stm32
  - GOAL=unix
  - GOAL=src

matrix:
  exclude:
    - compiler: clang
      env: GOAL=stm32
    - compiler: clang
      env: GOAL=src

addons:
  apt:
    packages:
    - build-essential
    - gcc-multilib
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi

install:
    - pip3 install ed25519 pyblake2
    - pip3 install flake8
    - pip3 install ecdsa mnemonic protobuf requests

script:
  - test "$GOAL" != "stm32" || make vendorheader
  - test "$GOAL" != "stm32" || make build_cross
  - test "$GOAL" != "stm32" || make build_boardloader
  - test "$GOAL" != "stm32" || make build_bootloader
  - test "$GOAL" != "stm32" || make build_firmware
  - test "$GOAL" != "stm32" || make sizecheck

  - test "$GOAL" != "unix" || make build_unix TREZOR_NOUI=1
  - test "$GOAL" != "unix" || make test
  - test "$GOAL" != "unix" || make testpy

  - test "$GOAL" != "src" || make style

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
