dist: trusty

language: c

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential gcc-multilib gcc-arm-embedded

before_script:
  - make build_unix TREZORUI_NOUI=1
  - make build_stmhal

script:
  - make test
