sudo: false
dist: trusty
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - check
    - cmake
    - cmake-data
    - libssl-dev
    - python-pip
    - valgrind

install:
  - pip install --user pytest ecdsa curve25519-donna

script:
  - make
  - ./tests/aestst
  - ./tests/test_check
  - CK_TIMEOUT_MULTIPLIER=20 valgrind -q --error-exitcode=1 ./tests/test_check
  - ./tests/test_openssl 1000
  - cd ./tests ; ITERS=10 pytest ; cd ..

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
